# Create a clusterrole with permissions required to read resources supported by the Command Set.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubernetes-command-set
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
      - pods
      - pods/log
      - namespaces
      - deployments
      - services
    verbs:
      - get
      - list
      - watch
# Create a service account named kubernetes-command-set.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-command-set
  namespace: default
---
# Bind the cluster role to the service account.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-command-set
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-command-set
subjects:
  - kind: ServiceAccount
    name: kubernetes-command-set
    namespace: default
